language: node_js
node_js:
  - "10.16.3"
addons:
  chrome: stable
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run lint
  - npm test -- --watch false --browsers ChromeHeadless
